{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "zeebe-operate.fullname" . }}
  labels: {{ include "zeebe-operate.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "zeebe-operate.fullname" . }}
              servicePort: 80
{{- end }}