global:
  zeebe: "{{ .Release.Name }}-zeebe" #the zeebe service instance where operate will connect
  elasticsearch:
    host: "elasticsearch-master"
    port: 9200
    clusterName: "elasticsearch"
service:
  type: ClusterIP
  port: 80
image:
  repository: camunda/operate
  tag: 1.2.0-alpha2

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi


nodeSelector: 

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    
  path: /
  host: 

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
